Add type NodePort to SVC in Inbox
NBISweden/LocalEGA-helm pull request #28
Opened 2019-04-03 20:08 UTC by blankdots

### Describe the pull request:

- [x] Bug fix

### Pull request long description:
Prevents the following failure if one wants to specify `NodePort` to `Inbox` (unless I missed something):
```
╰─$ helm install --name lega --namespace lega localega -f localega/values.yaml -f localega/config/trace.yml
Error: release lega failed: Service "lega-localega-inbox" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

2019-04-03 21:10 UTC, jonandernovella commented
In my opinion this approach is not the best for defining a service type. It might be better to template the `type`. In this case, it is`nodePort` the one which should have the value check, IMO.

2019-04-03 21:17 UTC, blankdots commented
@jonandernovella you mean these lines: https://github.com/NBISweden/LocalEGA-helm/blob/master/ega-charts/localega/templates/inbox-svc.yaml#L12-L14 ? Because apparently that is not enough.

2019-04-03 21:19 UTC, jonandernovella commented
They are not enough, indeed. You also need to add the `type`, otherwise it will still think it's `ClusterIP`, since it's default.

2019-04-03 21:21 UTC, blankdots commented
ok, we can talk later about how to do this, I was just looking for a simple fix :)

2019-04-08 20:08 UTC, blankdots commented
@jonandernovella how about now?

2019-04-09 06:44 UTC, jonandernovella submitted a review, later dismissed
Perfect!

2019-04-09 06:44 UTC, jonandernovella commented
LGTM!

2019-04-15 05:52 UTC, jbygdell requested changes
You might as well fix the related stuff:
https://github.com/NBISweden/LocalEGA-helm/blob/de5bb8d0715ab95eb82c0c154ec084e838502e52/ega-charts/localega/templates/inbox-svc.yaml#L13:L14

In the vlaues.yaml the port specifications is `port` not `nodePort`.
Also the specifications for `nodePort` is in the range of `30000-32767`, we might want to make sure that there is no conflicts with the specified `port` value.

There are more stuff here
https://kubernetes.io/docs/concepts/services-networking/service/#nodeport

2019-04-15 07:51 UTC, jbygdell submitted a review, later dismissed

2019-04-15 07:52 UTC, jonandernovella commented
@jbygdell Bump the chart version before merge?

2019-04-16 06:40 UTC, jbygdell approved these changes

2019-04-16 09:18 UTC, jonandernovella approved these changes

2019-04-16 09:19 UTC, merged