Rename conf directory in cega to config
NBISweden/LocalEGA-helm pull request #53
Opened 2019-11-04 13:46 UTC by viklund

This way the config directory has the same name for both charts.

### Describe the pull request:

- [x] Functional change

### Pull request long description:
Rename the conf dir in the cega chart into config so it is consistent between the two charts.

2019-11-05 06:03 UTC, blankdots reviewed
curious that it fails, took a look however could not figure out why:
> waiting for fake cega to become ready

Also a version bump would be nice: https://github.com/NBISweden/LocalEGA-helm/blob/master/ega-charts/cega/Chart.yaml#L9

2019-11-05 06:48 UTC, jbygdell commented
One of the nodes had failed, that prevented complete cleanup so some resources where still lingering in the system.

2019-11-05 08:26 UTC, blankdots submitted a review, later dismissed

2019-11-05 08:27 UTC, jbygdell requested changes
I think we should have the static files in a separate directory.

2019-11-07 08:03 UTC, jbygdell approved these changes

2019-11-07 08:07 UTC, blankdots approved these changes

2019-11-07 09:29 UTC, merged