Feature/config updates
NBISweden/LocalEGA-helm pull request #8
Opened 2019-01-31 07:23 UTC by jbygdell

### Describe the pull request:

- [X] Bug fix
- [X] Functional change
- [ ] New feature
- [X] Code cleanup
- [ ] Build system change
- [X] Documentation change
- [ ] Language translation

### Pull request long description:

This i a major update for the helm chart and it is done in preparation for upstream changes to among other things new docker images.

### Changes made:

1. Separate image entries for each of the services.
2. All options in the `defaults.ini` file are now available as ENV.
3. Secrets and config maps can no longer be excluded during deployment.
4. S3 related configs have been renamed to better reflect their position.

### Related issues:

### Additional information:

### Release note:

Version bumped to `v0.2.0`

### Documentation change:

### Mentions:

2019-02-03 18:33 UTC, blankdots requested changes
Review: first part see comments.

I have yet to test the charts, and I will do so in 2nd part.

2019-02-03 18:33 UTC, blankdots commented on ega-charts/localega/templates/mapper-deploy.yaml
> +          value: "debug"
I see in other places this used: ` value: {{ .Values.config.log | quote }}`

2019-02-03 18:33 UTC, blankdots commented on ega-charts/localega/templates/mapper-deploy.yaml
> +          value: "disable"
maybe a  miss on this: `{{ .Values.config.broker_enable_ssl | quote }}`

2019-02-03 18:33 UTC, blankdots commented on ega-charts/localega/templates/verify-deploy.yaml
> +          value: "debug"
`value: {{ .Values.config.log | quote }}`

2019-02-03 18:33 UTC, blankdots commented on ega-charts/localega/templates/verify-deploy.yaml
> +          value: "disable"
`{{ .Values.config.broker_enable_ssl | quote }}`

2019-02-03 18:33 UTC, blankdots commented on ega-charts/localega/values.yaml
> +  log: "default"
I propose to use `debug` to use as default.

2019-02-03 18:33 UTC, blankdots commented on README.md
> +`config.cega_port` | CEGA MQ acces port | `5272`
I think this is the default port when connecting to CRG ? but it should be `5672` i assume most people will use the default RabbitMQ - but not a hard requirement

In the `values.yml` i see it is `5672`

2019-02-04 08:26 UTC, jbygdell commented on ega-charts/localega/templates/verify-deploy.yaml
> +          value: "disable"
No those are different, this is if we need SSL for the connectin to the postgres sever.

2019-02-04 08:30 UTC, jbygdell commented on ega-charts/localega/templates/mapper-deploy.yaml
> +          value: "disable"
This is a part that is not fully implemented yet as out postgres don't accept ssl connections as it is.

2019-02-04 09:19 UTC, blankdots commented on ega-charts/localega/templates/mapper-deploy.yaml
> +          value: "disable"
My bad ... I think I meant to write this: `{{ .Values.config.postgres_sslmode | quote }}` in `ingest-deploy` I think it should be everywhere the same.

2019-02-04 09:19 UTC, blankdots commented on ega-charts/localega/templates/verify-deploy.yaml
> +          value: "disable"
`{{ .Values.config.postgres_sslmode | quote }}` - mistake meant this :disappointed:

2019-02-05 09:51 UTC, jonandernovella requested changes
When working with string data, specially with secrets, it's  highly recommended **quoting the strings**. Don't do it with integers though. Regarding the new variable names, I think they are better than before.

2019-02-05 15:12 UTC, jonandernovella approved these changes
Good job! The rest looks fine to me.

2019-02-07 07:07 UTC, blankdots approved these changes

2019-02-07 07:08 UTC, merged